package com.easy.query.console.dto;


import com.easy.query.core.annotation.Column;
import com.easy.query.core.annotation.Navigate;
import com.easy.query.core.annotation.NavigateFlat;
import com.easy.query.core.enums.RelationTypeEnum;
import lombok.Data;
import lombok.ToString;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;

/**
 * this file automatically generated by easy-query struct dto mapping
 * 当前文件是easy-query自动生成的 结构化dto 映射
 * {@link com.easy.query.console.entity.Company }
 *
 * @author xuejiaming
 * @easy-query-dto schema: normal
 */
@Data
public class CompanyDTO2 {


    /**
     * 企业id
     */
    @Column(dbType = "varchar(32)", comment = "企业id")
    private String id;
    /**
     * 企业名称
     */
    @Column(nullable = false, comment = "企业名称")
    private String name;
    /**
     * 企业创建时间
     */
    @Column(comment = "企业创建时间")
    private LocalDateTime createTime;
    /**
     * 注册资金
     */
    @Column(comment = "注册资金")
    private BigDecimal registerMoney;


    @NavigateFlat(pathAlias = "users.cards.name")
    private String bankCardName;

    @NavigateFlat(pathAlias = "")
    private String bankCardName2;



}
